import * as vscode from 'vscode';

export type Locale = 'en' | 'zh';
export type LocaleSetting = 'auto' | Locale;
export type Translator = (key: keyof typeof messages['en'], params?: Record<string, any>) => string;

const messages = {
    en: {
        'warning.dbNotFound': 'Cursor database not found. Make sure you are using Cursor IDE.',
        'info.saved': 'Chat history saved',
        'markdown.generatedBy': 'Generated by LLM Chat History Extension',
        'markdown.cursorSession': 'Cursor Session {id} ({date})',
        'markdown.untitled': 'Untitled',
        'markdown.created': 'Created',
        'markdown.messages': 'Messages',
        'markdown.user': 'User',
        'markdown.assistant': 'Assistant',
        'markdown.system': 'System',
        'markdown.sessionId': 'Session ID',
        'markdown.workspace': 'Workspace',
        'markdown.toolUses': 'Tool Uses',
        'markdown.toolResults': 'Tool Results',
        'speaker.user': 'User ({time})',
        'speaker.agent': 'Agent{info}',
        'section.thoughtProcess': 'Thought Process',
        'toolUse.title': 'Tool use: **{name}**',
        'toolUse.status': 'Status: {status}',
        'toolUse.args': 'Args',
        'toolUse.result': 'Result',
        'mode.chat': 'Chat',
        'mode.agent': 'Agent',
        'toolUse.summary.grep': 'Grep for "{pattern}" in "{path}" • {matches} matches',
        'toolUse.summary.list_dir': 'Listed directory {dir} • {count} results',
        'toolUse.summary.read_file': 'Read file: {file}',
        'toolUse.summary.web_search': 'Web search for "{query}" • {count} results',
        'toolUse.summary.codebase_search': 'Code search for "{query}"',
        'toolUse.summary.run_terminal_cmd': 'Run command: {command}',
        'toolUse.summary.glob_file_search': 'Glob search "{pattern}" • {count} files',
        'toolUse.summary.write': 'Edit file: {file}',
        'toolUse.summary.search_replace': 'Search/replace in {file}',
    },
    zh: {
        'warning.dbNotFound': '未找到 Cursor 数据库，请确认已安装并使用 Cursor IDE。',
        'info.saved': '聊天记录已保存',
        'markdown.generatedBy': '由 LLM Chat History 扩展生成',
        'markdown.cursorSession': 'Cursor 会话 {id}（{date}）',
        'markdown.untitled': '未命名',
        'markdown.created': '创建时间',
        'markdown.messages': '消息',
        'markdown.user': '用户',
        'markdown.assistant': '助手',
        'markdown.system': '系统',
        'markdown.sessionId': '会话ID',
        'markdown.workspace': '工作区',
        'markdown.toolUses': '工具调用',
        'markdown.toolResults': '工具结果',
        'speaker.user': '用户（{time}）',
        'speaker.agent': '助手{info}',
        'section.thoughtProcess': '思考过程',
        'toolUse.title': '工具调用：**{name}**',
        'toolUse.status': '状态：{status}',
        'toolUse.args': '参数',
        'toolUse.result': '结果',
        'mode.chat': '对话',
        'mode.agent': 'Agent',
        'toolUse.summary.grep': 'Grep 搜索 "{pattern}" 于 "{path}" • {matches} 条结果',
        'toolUse.summary.list_dir': '列出目录 {dir} • {count} 个结果',
        'toolUse.summary.read_file': '读取文件：{file}',
        'toolUse.summary.web_search': '网页搜索 "{query}" • {count} 条结果',
        'toolUse.summary.codebase_search': '代码搜索 "{query}"',
        'toolUse.summary.run_terminal_cmd': '执行命令：{command}',
        'toolUse.summary.glob_file_search': 'Glob 搜索 "{pattern}" • {count} 个文件',
        'toolUse.summary.write': '编辑文件：{file}',
        'toolUse.summary.search_replace': '查找替换：{file}',
    }
};

export function resolveLocale(setting: LocaleSetting | undefined): Locale {
    if (setting === 'en' || setting === 'zh') return setting;
    const vscodeLang = vscode.env.language.toLowerCase();
    if (vscodeLang.startsWith('zh')) return 'zh';
    return 'en';
}

export function createTranslator(setting?: LocaleSetting): Translator {
    const locale = resolveLocale(setting);
    return (key, params = {}) => {
        const dict = messages[locale] || messages.en;
        const template = dict[key] ?? messages.en[key] ?? key;
        return template.replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ''));
    };
}

