/**
 * Markdown Parser 测试用例
 * 基于实际 markdown 文件格式和数据库结构生成
 * 
 * 运行测试：
 * - 使用 Vitest: npm install -D vitest @vitest/ui && npx vitest
 * - 使用 Jest: npm install -D jest @types/jest ts-jest && npx jest
 */

import { parseMarkdown, ParsedSession } from './markdown-parser';
import { SyncMessage } from './cloud/cloud-sync';

describe('MarkdownParser', () => {
    describe('Session ID 提取', () => {
        it('应该从注释中提取 Session ID (格式1)', () => {
            const content = `<!-- Generated by LLM Chat History Extension -->
<!-- Cursor Session 9f1fcedc-00cb-4deb-9de8-c273c1951a92 (2026-01-07 12:18Z) -->

# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result).not.toBeNull();
            expect(result?.session_id).toBe('9f1fcedc-00cb-4deb-9de8-c273c1951a92');
        });

        it('应该从 Markdown 元数据中提取 Session ID (格式2)', () => {
            const content = `# Test Session

**Session ID**: \`abc123-def456\`

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.session_id).toBe('abc123-def456');
        });

        it('应该从中文格式中提取 Session ID (格式3)', () => {
            const content = `# Test Session

**会话ID**: \`test-session-123\`

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.session_id).toBe('test-session-123');
        });

        it('应该从文件路径生成 Session ID（当没有找到时）', () => {
            const content = `# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/workspace/.llm-chat-history/history/test-file.md');
            expect(result?.session_id).toBe('file-test-file');
        });
    });

    describe('标题提取', () => {
        it('应该提取第一个 # 标题', () => {
            const content = `# My Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.title).toBe('My Test Session');
        });

        it('应该使用 "Untitled" 当没有标题时', () => {
            const content = `## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.title).toBe('Untitled');
        });
    });

    describe('Source 提取', () => {
        it('应该识别 Cursor source', () => {
            const content = `<!-- Cursor Session: test-123 -->

# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.source).toBe('cursor');
        });

        it('应该识别 Cline source', () => {
            const content = `<!-- Cline Session: test-123 -->

# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.source).toBe('cline');
        });

        it('应该识别 Blackbox source', () => {
            const content = `<!-- Blackbox Session: test-123 -->

# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.source).toBe('blackboxai');
        });

        it('应该识别 Kilo source', () => {
            const content = `<!-- Kilo Session: test-123 -->

# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.source).toBe('kilo');
        });

        it('应该默认使用 cursor source', () => {
            const content = `# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.source).toBe('cursor');
        });
    });

    describe('Workspace 信息提取', () => {
        it('应该从文件路径提取 workspace 信息', () => {
            const content = `# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(
                content,
                '/Users/clark/Project/my-project/.llm-chat-history/history/test.md'
            );
            expect(result?.workspace_path).toBe('/Users/clark/Project/my-project');
            expect(result?.workspace_name).toBe('my-project');
        });

        it('应该处理 Windows 路径', () => {
            const content = `# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(
                content,
                'C:\\Users\\clark\\Project\\my-project\\.llm-chat-history\\history\\test.md'
            );
            expect(result?.workspace_path).toBe('C:\\Users\\clark\\Project\\my-project');
            expect(result?.workspace_name).toBe('my-project');
        });

        it('应该返回空对象当路径不包含 .llm-chat-history 时', () => {
            const content = `# Test Session

## 💬 User #1
_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.workspace_path).toBeUndefined();
            expect(result?.workspace_name).toBeUndefined();
        });
    });

    describe('消息解析', () => {
        it('应该解析基本的 User 消息', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18Z_

Hello, this is a test message.`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages).toHaveLength(1);
            expect(result?.messages[0].type).toBe('user');
            expect(result?.messages[0].content).toBe('Hello, this is a test message.');
            expect(result?.messages[0].timestamp).toBe('2026-01-07T12:18:00.000Z');
        });

        it('应该解析基本的 Assistant 消息', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

This is an assistant response.`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages).toHaveLength(1);
            expect(result?.messages[0].type).toBe('assistant');
            expect(result?.messages[0].content).toBe('This is an assistant response.');
        });

        it('应该解析带模型名称的 Assistant 消息', () => {
            const content = `# Test Session

## 🤖 Assistant #1 (gpt-4, Agent)

_2026-01-07 12:19Z_

Response text.`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].model_name).toBe('gpt-4');
            expect(result?.messages[0].mode).toBe('Agent');
        });

        it('应该解析中文格式的消息标题', () => {
            const content = `# Test Session

## 💬 用户 #1

_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].type).toBe('user');
        });

        it('应该解析多个消息', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18Z_

Question 1

---

## 🤖 Assistant #2

_2026-01-07 12:19Z_

Answer 1

---

## 💬 User #3

_2026-01-07 12:20Z_

Question 2`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages).toHaveLength(3);
            expect(result?.messages[0].type).toBe('user');
            expect(result?.messages[1].type).toBe('assistant');
            expect(result?.messages[2].type).toBe('user');
        });
    });

    describe('时间戳解析', () => {
        it('应该解析标准时间戳格式 (YYYY-MM-DD HH:MMZ)', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].timestamp).toBe('2026-01-07T12:18:00.000Z');
        });

        it('应该解析带秒的时间戳格式 (YYYY-MM-DD HH:MM:SSZ)', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18:30Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].timestamp).toBe('2026-01-07T12:18:30.000Z');
        });

        it('应该为没有时间戳的消息生成估算时间戳', () => {
            const content = `# Test Session

## 💬 User #1

Hello without timestamp`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].timestamp).toBeDefined();
            expect(result?.messages[0].timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
        });

        it('应该按时间戳排序消息', () => {
            const content = `# Test Session

## 💬 User #2

_2026-01-07 12:20Z_

Message 2

---

## 💬 User #1

_2026-01-07 12:18Z_

Message 1

---

## 💬 User #3

_2026-01-07 12:22Z_

Message 3`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages).toHaveLength(3);
            expect(result?.messages[0].content).toBe('Message 1');
            expect(result?.messages[1].content).toBe('Message 2');
            expect(result?.messages[2].content).toBe('Message 3');
        });
    });

    describe('思考过程解析', () => {
        it('应该解析思考过程 (Thinking Process)', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

<details>
<summary><strong>💭 Thinking Process</strong></summary>

> This is the thinking process.
> It can span multiple lines.

</details>

This is the response.`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].thinking).toContain('This is the thinking process.');
            expect(result?.messages[0].content).toContain('This is the response.');
        });

        it('应该解析中文思考过程', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

<details>
<summary><strong>💭 思考过程</strong></summary>

> 这是思考过程。

</details>

这是回复。`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].thinking).toContain('这是思考过程。');
        });
    });

    describe('工具调用解析', () => {
        it('应该解析单个工具调用', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

**🔧 Tool Uses** (1)

<details>
<summary>🔧 **read_file_v2**</summary>

_Status: completed_

**Args**

\`\`\`json
{
  "path": "/test/file.ts"
}
\`\`\`

**Result**

\`\`\`json
{
  "contents": "file content",
  "totalLinesInFile": 100
}
\`\`\`
</details>`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].tool_uses).toBeDefined();
            
            const toolUses = JSON.parse(result!.messages[0].tool_uses!);
            expect(toolUses).toHaveLength(1);
            expect(toolUses[0].name).toBe('read_file_v2');
            expect(toolUses[0].status).toBe('completed');
            expect(toolUses[0].input).toEqual({ path: '/test/file.ts' });
            expect(toolUses[0].result).toEqual({ contents: 'file content', totalLinesInFile: 100 });
        });

        it('应该解析多个工具调用', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

**🔧 Tool Uses** (2)

<details>
<summary>🔧 **read_file_v2**</summary>

_Status: completed_

**Args**

\`\`\`json
{"path": "/file1.ts"}
\`\`\`
</details>

<details>
<summary>🔧 **codebase_search**</summary>

_Status: completed_

**Args**

\`\`\`json
{"query": "test query"}
\`\`\`
</details>`;

            const result = parseMarkdown(content, '/test/path.md');
            const toolUses = JSON.parse(result!.messages[0].tool_uses!);
            expect(toolUses).toHaveLength(2);
            expect(toolUses[0].name).toBe('read_file_v2');
            expect(toolUses[1].name).toBe('codebase_search');
        });

        it('应该解析转义的 JSON 字符串', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

**🔧 Tool Uses** (1)

<details>
<summary>🔧 **create_plan**</summary>

_Status: completed_

**Args**

\`\`\`json
"{\\"plan\\":\\"test plan\\",\\"name\\":\\"Test\\"}"
\`\`\`
</details>`;

            const result = parseMarkdown(content, '/test/path.md');
            const toolUses = JSON.parse(result!.messages[0].tool_uses!);
            expect(toolUses[0].input).toEqual({ plan: 'test plan', name: 'Test' });
        });

        it('应该解析不同格式的工具名称', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

**🔧 Tool Uses** (1)

<details>
<summary><strong>tool_name</strong></summary>

_Status: completed_

**Args**

\`\`\`json
{}
\`\`\`
</details>`;

            const result = parseMarkdown(content, '/test/path.md');
            const toolUses = JSON.parse(result!.messages[0].tool_uses!);
            expect(toolUses[0].name).toBe('tool_name');
        });

        it('应该解析中文工具调用标题', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

**🔧 工具调用** (1)

<details>
<summary>🔧 **read_file_v2**</summary>

_Status: completed_

**Args**

\`\`\`json
{}
\`\`\`
</details>`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].tool_uses).toBeDefined();
        });
    });

    describe('边界情况', () => {
        it('应该处理空文件', () => {
            const result = parseMarkdown('', '/test/path.md');
            expect(result).toBeNull();
        });

        it('应该处理没有消息的文件', () => {
            const content = `# Test Session

This is just a title with no messages.`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result).toBeNull();
        });

        it('应该处理只有标题行的消息', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18Z_

`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages).toHaveLength(1);
            expect(result?.messages[0].content).toBe('');
        });

        it('应该处理多行内容', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18Z_

Line 1
Line 2
Line 3`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].content).toBe('Line 1\nLine 2\nLine 3');
        });

        it('应该处理特殊字符', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18Z_

Message with \`code\` and **bold** and *italic*`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].content).toContain('`code`');
            expect(result?.messages[0].content).toContain('**bold**');
        });

        it('应该处理无效的时间戳格式', () => {
            const content = `# Test Session

## 💬 User #1

_Invalid timestamp_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            expect(result?.messages[0].timestamp).toBeDefined();
            // 应该生成估算时间戳
        });

        it('应该处理工具调用解析失败的情况', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

**🔧 Tool Uses** (1)

<details>
<summary>🔧 **invalid_tool**</summary>

**Args**

\`\`\`json
{ invalid json }
\`\`\`
</details>`;

            const result = parseMarkdown(content, '/test/path.md');
            // 应该仍然解析工具名称，即使 JSON 解析失败
            const toolUses = JSON.parse(result!.messages[0].tool_uses!);
            expect(toolUses[0].name).toBe('invalid_tool');
            expect(toolUses[0].input).toBe('{ invalid json }');
        });
    });

    describe('完整会话解析', () => {
        it('应该解析完整的 Cursor 会话', () => {
            const content = `<!-- Generated by LLM Chat History Extension -->
<!-- Cursor Session 9f1fcedc-00cb-4deb-9de8-c273c1951a92 (2026-01-07 12:18Z) -->

# Cursor workspace chat history markdown

**Created**: 2026-01-07 12:18Z  
**Messages**: 2 (User: 1, Assistant: 1)  
**Session ID**: \`9f1fcedc-00cb-4deb-9de8-c273c1951a92\`

---

## 💬 User #1

_2026-01-07 12:18Z_

帮我看下，在cursor workspace模式下，为什么聊天记录生成markdown文件保存下来

---

## 🤖 Assistant #2 (Agent)

_2026-01-07 12:18Z_

<details>
<summary><strong>💭 Thinking Process</strong></summary>

> 用户想了解在Cursor workspace模式下，为什么聊天记录会生成markdown文件保存下来。

</details>

让我先查看相关代码来理解Cursor workspace模式下聊天记录保存为markdown的逻辑。

**🔧 Tool Uses** (1)

<details>
<summary>🔧 **read_file_v2**</summary>

_Status: completed_

**Args**

\`\`\`json
{
  "path": "/test/file.ts"
}
\`\`\`

**Result**

\`\`\`json
{
  "contents": "file content",
  "totalLinesInFile": 100
}
\`\`\`
</details>`;

            const result = parseMarkdown(
                content,
                '/Users/clark/Project/test/.llm-chat-history/history/test.md'
            );

            expect(result).not.toBeNull();
            expect(result?.session_id).toBe('9f1fcedc-00cb-4deb-9de8-c273c1951a92');
            expect(result?.title).toBe('Cursor workspace chat history markdown');
            expect(result?.source).toBe('cursor');
            expect(result?.workspace_path).toBe('/Users/clark/Project/test');
            expect(result?.workspace_name).toBe('test');
            expect(result?.messages).toHaveLength(2);

            // 检查 User 消息
            expect(result?.messages[0].type).toBe('user');
            expect(result?.messages[0].content).toContain('帮我看下');

            // 检查 Assistant 消息
            expect(result?.messages[1].type).toBe('assistant');
            expect(result?.messages[1].mode).toBe('Agent');
            expect(result?.messages[1].thinking).toContain('用户想了解');
            expect(result?.messages[1].content).toContain('让我先查看相关代码');
            expect(result?.messages[1].tool_uses).toBeDefined();

            const toolUses = JSON.parse(result!.messages[1].tool_uses!);
            expect(toolUses).toHaveLength(1);
            expect(toolUses[0].name).toBe('read_file_v2');
        });
    });

    describe('数据库兼容性', () => {
        it('应该生成符合数据库结构的消息格式', () => {
            const content = `# Test Session

## 💬 User #1

_2026-01-07 12:18Z_

Hello`;

            const result = parseMarkdown(content, '/test/path.md');
            const message = result!.messages[0];

            // 验证字段与 chat_messages 表结构匹配
            expect(message.type).toBeDefined(); // type: VARCHAR NOT NULL
            expect(message.content).toBeDefined(); // content: TEXT
            expect(message.timestamp).toBeDefined(); // timestamp: TIMESTAMP WITH TIME ZONE NOT NULL
            expect(typeof message.timestamp).toBe('string');
            expect(message.timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);

            // 可选字段
            // thinking: TEXT
            // model_name: VARCHAR
            // mode: VARCHAR
            // context: TEXT
            // tool_results: TEXT (JSON string)
            // tool_uses: TEXT (JSON string)
            // images: TEXT (JSON string)
        });

        it('应该将 tool_uses 存储为 JSON 字符串', () => {
            const content = `# Test Session

## 🤖 Assistant #1

_2026-01-07 12:19Z_

**🔧 Tool Uses** (1)

<details>
<summary>🔧 **test_tool**</summary>

**Args**

\`\`\`json
{"key": "value"}
\`\`\`
</details>`;

            const result = parseMarkdown(content, '/test/path.md');
            const toolUses = result!.messages[0].tool_uses;

            expect(toolUses).toBeDefined();
            expect(typeof toolUses).toBe('string');
            
            // 验证是有效的 JSON
            const parsed = JSON.parse(toolUses!);
            expect(Array.isArray(parsed)).toBe(true);
        });
    });
});
